# Generated by Django 2.2.4 on 2019-08-12 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ISBN',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='Id',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
